import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { parseCityOSPuckRegistration, digestCityOSPuckRegistration, bindCityOSPuckRegistration } from '../../packages/core/cityos-registration.ts';

// Generated by CityOS Compiler at platform commit 6fa123d09ba43d3117f1cb15bed1e4c59d3e45bf.
// This is a copied conformance artifact, never a copied implementation or production admission.
const bytes = readFileSync(new URL('./fixtures/compiler-registration.v1.json', import.meta.url), 'utf8');
const fixture = () => JSON.parse(bytes);
const registrationDigest = 'sha256:b8244096f4aa91b86e80271f574a14341cc2f598e58b2d6d8d6f4404a222010b';
const artifactDigest = 'sha256:e55e668a4c9a0c7ef6b3838c7a6177bda804ca734ff84a593a69accec77a2933';
function installed() {
  return new Map(['root', 'message'].map(key => [`fixture.${key}`, {
    kind: key === 'root' ? 'root' : 'component', version: '1',
    digest: 'sha256:' + 'a'.repeat(64), enabled: true,
    render: props => props,
  }]));
}

test('the exact compiler artifact has the fork digest, distinct from its byte digest', async () => {
  assert.equal('sha256:' + createHash('sha256').update(bytes).digest('hex'), artifactDigest);
  assert.equal(await digestCityOSPuckRegistration(fixture()), registrationDigest);
  assert.notEqual(artifactDigest, registrationDigest);
  assert.equal(parseCityOSPuckRegistration(fixture()).source.ownerId, 'core.cms');
});
test('generated Arabic, integer, enum and root-slot contracts bind without manual field conversion', async () => {
  const renderers = installed();
  const config = await bindCityOSPuckRegistration(fixture(), registrationDigest, key => renderers.get(key));
  assert.equal(config.components.FixtureMessage.label, 'رسالة');
  assert.deepEqual(config.components.FixtureMessage.fields.level, { type: 'number', label: 'المستوى', min: 1, max: 6, step: 1 });
  assert.deepEqual(config.root.fields.content.allow, ['FixtureMessage']);
  assert.equal(config.components.FixtureMessage.fields.tone.options[1].label, 'تنبيه');
  assert.deepEqual(config.components.FixtureMessage.render({ title: 'اختبار' }), { title: 'اختبار' });
});
test('the artifact byte hash cannot substitute for independently admitted registration digest', async () => {
  const renderers = installed();
  await assert.rejects(bindCityOSPuckRegistration(fixture(), artifactDigest, key => renderers.get(key)), /MANIFEST_MISMATCH/);
});
test('changing compiler metadata does not preserve acceptance under the original digest', async () => {
  const input = fixture(); input.components[0].fields.level.max = 900;
  const renderers = installed();
  await assert.rejects(bindCityOSPuckRegistration(input, registrationDigest, key => renderers.get(key)), /MANIFEST_MISMATCH/);
});
test('a cached compiler-derived renderer stops executing after revocation or artifact replacement', async () => {
  for (const mutate of [renderer => { renderer.enabled = false; }, renderer => { renderer.digest = 'sha256:' + 'b'.repeat(64); }]) {
    const renderers = installed();
    const config = await bindCityOSPuckRegistration(fixture(), registrationDigest, key => renderers.get(key));
    mutate(renderers.get('fixture.message'));
    assert.throws(() => config.components.FixtureMessage.render({ title: 'denied' }), /RENDERER_UNAVAILABLE/);
  }
});
